version: "3.9"
services:
  app:
    build:
      dockerfile: Dockerfile
      context: .
      target: dev
    environment:
      HOST: 127.0.0.1
    ports:
      - "4000:4000"
    expose:
      - "4000"
    volumes:
      - ./:/app/
    networks:
      - skynet

networks:
  skynet:
    driver: bridge
